# NOTE: Generated By HttpRunner v3.1.11
# FROM: .\testcases\browser_index.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from api.api_v1_browser_index_test import TestCaseApiV1BrowserIndex as ApiV1BrowserIndex


class TestCaseBrowserIndex(HttpRunner):

    config = (
        Config("至信链浏览器index").base_url("https://zxscanapi.qq.com/api/v1").verify(False)
    )

    teststeps = [
        Step(
            RunTestCase("至信链浏览器index")
            .with_variables(**{"nftId": ""})
            .call(ApiV1BrowserIndex)
            .validate()
            .assert_equal("body.retMsg", "请求成功")
        ),
    ]


if __name__ == "__main__":
    TestCaseBrowserIndex().test_start()
