# NOTE: Generated By HttpRunner v3.1.11
# FROM: .\testcases\site_info.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from api.api_site_info_test import TestCaseApiSiteInfo as ApiSiteInfo


class TestCaseSiteInfo(HttpRunner):

    config = Config("site info").base_url("https://www.v2ex.com").verify(False)

    teststeps = [
        Step(
            RunTestCase("request site info")
            .with_variables(**{"id": "1"})
            .call(ApiSiteInfo)
        ),
    ]


if __name__ == "__main__":
    TestCaseSiteInfo().test_start()
