# NOTE: Generated By HttpRunner v3.1.11
# FROM: api\api_v1_browser_index.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseApiV1BrowserIndex(HttpRunner):

    config = Config("test")

    teststeps = [
        Step(
            RunRequest("test")
            .with_variables(**{"nftId": ""})
            .get("/browser/index")
            .with_headers(**{"Content-Type": "application/json;charset=utf-8"})
        ),
    ]


if __name__ == "__main__":
    TestCaseApiV1BrowserIndex().test_start()
