# NOTE: Generated By HttpRunner v3.1.11
# FROM: api\api_site_info.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseApiSiteInfo(HttpRunner):

    config = Config("site info api")

    teststeps = [
        Step(
            RunRequest("site info api")
            .with_variables(**{"id": ""})
            .get("/api/nodes/show.json")
            .with_params(**{"id": "$id"})
        ),
    ]


if __name__ == "__main__":
    TestCaseApiSiteInfo().test_start()
