# NOTE: Generated By HttpRunner v3.1.11
# FROM: .\api\api_v1_nft_info.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseApiV1NftInfo(HttpRunner):

    config = Config("nft info")

    teststeps = [
        Step(
            RunRequest("nft info")
            .with_variables(
                **{
                    "secretId": "",
                    "secretKey": "",
                    "signData": "{generateApiSign($secretId,$secretKey)}",
                    "traceId": "{traceId()}",
                    "nftId": "",
                }
            )
            .get("http://175.27.11.195:80/api/v1/nft/info")
            .with_params(**{"nftId": "$nftId"})
            .with_headers(
                **{
                    "Content-Type": "application/json;charset=utf-8",
                    "Signature-Time": "{getMapValue($signData,SignatureTime)}",
                    "Signature": "{getMapValue($signData,Signature)}",
                    "Cloud-Trace-Id": "$traceId",
                    "Secret-Id": "$secretId",
                    "Nonce": "{getMapValue($signData,Nonce)}",
                }
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseApiV1NftInfo().test_start()
